Fixed the Fire Enchantment
Zedly/Zenchantments pull request #38
Opened 2020-05-12 09:09 UTC by Geolykt

The Fire enchantment would not work as  intended as the BlockBreakEvent was passed for some reason before it was cancelled, makeing sure that the event would be passed last would make sure that it wouldn't be canceled after it was recieved.

THIS COMMIT _MAY_ HAVE UNINTEDED SIDE EFFECTS

2020-06-16 20:18 UTC, rfrowe commented
Hi @Geolykt, thanks for the code. Please fix up your indentation. It seems that some lines in your diff are indented with spaces and some with tabs. This repository is styled with 4-space indentations.

2020-06-17 08:01 UTC, Geolykt commented
yea, I will fix that now

2020-06-21 15:27 UTC, Geolykt commented
Alright, since I suppose this will lead to nowwhere, I closed this

2020-06-24 19:06 UTC, rfrowe reviewed
I understand that this PR has been open for a while, but I'm not willing to merge code with TODOs or FIXMEs. These comments should help you bring your code to a state where it can be merged.

2020-06-24 19:06 UTC, rfrowe commented on Zenchantments/src/main/java/zedly/zenchantments/WatcherEnchant.java
> +     * This method returns whether a block is protected by the plugin and whether it should be considered <br>
This method does not adhere to the contract specified in this comment. You describe this method as a getter but it has side effects. I understand this is mentioned via the `remove` parameter doc but you should also mention it in the doc body.

You only use this method with `remove == true` once, so my recommendation is that you remove the removal functionality from this method. Then, your usage above:

```java
isProtectedBlock(block, true);
```

becomes:

```java
if (isProtectedBlock(block)) {
    NetherStep.netherstepLocs.remove(block);
    FrozenStep.frozenstepLocs.remove(block);
}
```

In the event that we need to do this elsewhere, I'd recommend that you just create a method `removeBlock` which encapsulates this functionality. Then your usage would be:

```java
if (isProtectedBlock(block)) {
    removeBlock(block);
}
```

Since my suggestion below changes your implementation from O(n) complexity to O(1), this refactor would yield better code with essentially no performance loss.

2020-06-26 21:10 UTC, rfrowe requested changes

2020-06-26 21:10 UTC, rfrowe commented on Zenchantments/src/main/java/zedly/zenchantments/WatcherEnchant.java
> +        return NetherStep.netherstepLocs.containsKey(block.getLocation()) || FrozenStep.frozenLocs.containsKey(block.getLocation());
Looks great! Did you test that this works?

2020-06-26 21:10 UTC, rfrowe commented on Zenchantments/src/main/java/zedly/zenchantments/WatcherEnchant.java
> +    public boolean isProtectedBlock(Block block) {
Can be `private`

2020-06-27 09:23 UTC, Geolykt commented on Zenchantments/src/main/java/zedly/zenchantments/WatcherEnchant.java
> +        return NetherStep.netherstepLocs.containsKey(block.getLocation()) || FrozenStep.frozenLocs.containsKey(block.getLocation());
yep, although only in 1.16.1, so without any NMS

2020-06-27 11:11 UTC, Geolykt commented on Zenchantments/src/main/java/zedly/zenchantments/WatcherEnchant.java
> +    public boolean isProtectedBlock(Block block) {
maybe also make it static since it doesn't call any methods that would require it to be aware of the instance? Although this has almost no effects I guess since it's private method

2020-06-30 20:36 UTC, rfrowe reviewed
@Zedly Can we test this? Let's get it in

2020-06-30 20:36 UTC, rfrowe approved these changes

2020-08-21 13:46 UTC, Geolykt commented
Due to severe changes in the project's layout I will not be able to push these changes. I will reopen a remastered version of this PR shortly

2020-08-21 13:46 UTC, closed without merging